name: kayan_app
description: تطبيق كيان مع ميزات AI وريلز
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  http: ^0.13.5
  shared_preferences: ^2.0.17
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  webview_flutter: ^4.2.2
  google_fonts: ^4.0.4
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
